### ISSUE TITLE
Syntax error due to using a reserved word as a column name in MySQL

### ISSUE THREAD

**Issue by zer0pool** [tokern/piicatcher#101]
Hello. 

I am trying to use piicatcher.  Thank you for this wonderful solution. 

and I have found a small issue that queries fail with syntax error due to using a reserved word as a column name in MySQL.
I have commited changes to my forked repository. I would like to make PR here to this repository if that is ok with you. 

https://github.com/zer0pool/piicatcher/commit/72e174d91ce2d1371517e129704aa5b8b532b0f5

**Comment by vrajat** [comment]
Hey,
Yes - definitely. This is a valid bug and the solution is correct. Minor changes maybe required. There are a couple of other places where columns lists are constructed. Also 1 test. We can discuss in the PR.

**Comment by zer0pool** [comment]
I have added testcases and changed other places where column names are used in query. 
waiting for your advice.

**Comment by vrajat** [comment]
@zer0pool can you take this survey (https://forms.gle/Ns6QSNvfj3Pr2s9s6) if you havent already ? This will help me understand what you are using/planning to use piicatcher for.

**Comment by zer0pool** [comment]
> @zer0pool can you take this survey (https://forms.gle/Ns6QSNvfj3Pr2s9s6) if you havent already ? This will help me understand what you are using/planning to use piicatcher for. 

I have already taken the survey. 😁
