### ISSUE TITLE
Try to get the column name which is having PII data, but sqlite -list-all returns nothing

### ISSUE THREAD

**Issue by prakhargoyal** [tokern/piicatcher#109]
@vrajat, as discussed with you on live chat, I am logging this sqlite db scanning issue which returns nothing.

I have a sqlite db, which is containing sample PII information, I have scanned it through sqlite --list-all but it returns nothing. I have tried sqlite --list-all --scan-type deep but nothing actually changed.  I have also tried to generate the catalog file, it also returns a blank file.

If I am just scanning the CSV file, than it only indicates that this file contains enum like Email, Person etc, but didn't tell actually which column is containing the PII information.

I want to identify which column is actually containing the which PII data, like which column is containg email data & which column is containing address information,

**Comment by prakhargoyal** [comment]
Here is the columns list which I have tried to scan
![Screenshot (4)](https://user-images.githubusercontent.com/1570738/87759404-e509e000-c82b-11ea-837f-db823266c96f.png)

**Comment by vrajat** [comment]
You had mentioned that this is from a public data set. Can you give me the link to this data set?

Do `maiden name`, `last name` and `first name` have a space? If yes, then the current regular expression will not match. 

`SSN`, `gender`, `address`, `city`, `state`, `zip` and `email` should have matched. I am checking if there is a bug. 

`birthdate` and `phone` are missing. I am tracking this task in #68
