### ISSUE TITLE
Import piicatcher in python files

### ISSUE THREAD

**Issue by prakhargoyal** [tokern/piicatcher#110]
Can we import this piicatcher library & use it in any program. As till now, I have only found the command line access of it, but what if I want to use it in any python program?

**Comment by vrajat** [comment]
Do you have a current use case where you want to import into an existing python application? 
Is there specific functionality of PIICatcher you need to use from another python file? (I understand that all the functionality should be exposed. I am trying to break down this task and prioritize sub-tasks.

**Comment by zer0pool** [comment]
@prakhargoyal 
You can make a class using a class of piicatcher. 
for example. here is the sample code I am using in my project. 
you need to look into the original code of piicatcher to understand 
which part of the class you need to import and how to initialte the task. 

```
from argparse import Namespace
from piicatcher.explorer.databases import RelDbExplorer

class PiiExtractor:

    report_filename_json = 'report.json'
    default_ns = Namespace(
        list_all=False,
        scan_type='deep',
        include_schema=(),
        exclude_schema=(),
        include_table=(),
        exclude_table=(),
        catalog={'format': 'json'}
    )

    def __init__(self, dbConf):
        self.ns = Namespace(**vars(self.default_ns))
        self.ns.connection_type = dbConf['connection_type']
        self.ns.host = dbConf['host']
        self.ns.user = dbConf['user']
        self.ns.password = dbConf['password']
        self.ns.database = dbConf['database']

    def run_db_explorer(self):
        with open(self.report_filename_json, "w") as output:
           self.ns.catalog['file'] = output
           RelDbExplorer.dispatch(self.ns)

if __name__ == '__main__':

    # Set db config
    dbConf = {
        'connection_type':'mysql',
        'host':'10.113.111.111',
        'password':'mypassword',
        'user':'myusername',
        'database':'logger'
    }

    et = PiiExtractor(dbConf)
    et.run_db_explorer()
```

**Comment by vrajat** [comment]
Yes. That is a good way to hack around the current interface. I do want to design and release an official API. Both your feedback will helpful. 

@zer0pool can you tell me a bit more about your project? What does your project do? I am trying to understand how you want to use PIICatcher programmatically.

**Comment by bryantbiggs** [comment]
I am interested in this as well - I would love to use this for interrogating log files in AWS to look for PII. I was hoping to use this package with a lambda function so that each new CloudWatch log stream can be interrogated in near real-time

**Comment by vrajat** [comment]
That is an interesting use case @bryantbiggs . I am in the process of designing an API. I'll add a proposal for you to review. How will you get access to the log stream ? Do you have to open a S3 file? Right now, PIICatcher does not support reading files from S3.

**Comment by bryantbiggs** [comment]
Thanks @vrajat ! I planned on getting the file contents through some means and then passing the contents to piicatcher. Following the event driven paradigm in AWS - we plan on listening to new CloudWatch log stream put events which would trigger a function to grab that log stream and then pass  it to piicatcher, and likewise with S3 put events: grab the file from S3 and pass it to piicatcher

**Comment by vrajat** [comment]
Then can the file API accept a file descriptor ? Something like:

    with open(...) as fp:
      scan_results = piicatcher.scan_fd(fp)

Then the API does not have to worry about how to get access to file contents.

**Comment by bryantbiggs** [comment]
exactly. if `piicatcher` has a way to accept [file like objects](https://docs.python.org/3/glossary.html#term-file-object) that would be a great start

**Comment by vrajat** [comment]
Please check [API docs](https://tokern.io/docs/piicatcher/api) to import and use PIICatcher functions
