### ISSUE TITLE
Best Practices for Automated Scans using PIICatcher

### ISSUE THREAD

**Issue by vrajat** [tokern/piicatcher#112]
@n2taylor @zer0pool 

I want to check in to see if you are continuing to use PIICatcher. 

I also want to find out if you have tried to automate or schedule piicatcher scan on your databases. I am getting questions on best practices to deploy and automate scans. Before I set best practices I want to find out from known users if they have tried to automate scans as well as what are the gaps and requirements.

Please tell me if you have any thoughts on this.

**Comment by vaidik** [comment]
We have this need as well

**Comment by vrajat** [comment]
@vaidik, have you been successful in automating scans ? Any feedback on what worked and what hasn't worked ?
