### ISSUE TITLE
Support for custom regular expressions

### ISSUE THREAD

**Issue by vaidik** [tokern/piicatcher#115]
Is there a way to add custom regular expressions? If not, having support that from configuration or another JSON file would be super useful and it will make piicatcher useful for a wider audience.

**Comment by vrajat** [comment]
Not yet. However this is a good feature addition. Right now, there a [RegexScanner](https://github.com/tokern/piicatcher/blob/master/piicatcher/scanner.py#L21) which uses [CommonRegex](https://pypi.org/project/commonregex/) for a list of regular expressions and maps it to [PIITypes](https://github.com/tokern/piicatcher/blob/master/piicatcher/piitypes.py). 

In a custom scanner, the list can be picked up from a json file. Each item in the list should consist of the regular expression and the PIIType it maps to. 

Does this sound reasonable? Are you open to contributing this feature?
