### ISSUE TITLE
piicatcher is not executing

### ISSUE THREAD

**Issue by kvrameshreddy** [tokern/piicatcher#126]
windows10 64-bit
python 3.8.7

Piicatcher installation is done without any errors.
When i try to run the piicatcher on csv files throws an error.
piicatcher files --path 'us-500.csv'  give error
![first_error](https://user-images.githubusercontent.com/49742709/108489589-bbd09700-72c7-11eb-95eb-905d2bffb90e.PNG)

After exploring google found a solution to this
Solution: pip uninstall python-magic
               pip install python-magic-bin==0.4.14
After i encounter with the below error
![second_error](https://user-images.githubusercontent.com/49742709/108490050-49ac8200-72c8-11eb-85d0-c131bc00672f.PNG)

Can you please help me in solving this.  The csv file used is from this link
[https://www.briandunning.com/sample-data/](url)

Thankyou.

**Comment by vrajat** [comment]
Did you install the spacy english pack?

    # Install Spacy English package
    python -m spacy download en_core_web_sm

**Comment by kvrameshreddy** [comment]
Hi @vrajat,
i have installed spacy english pacakge.

**Comment by vrajat** [comment]
Which version of spacy is installed?

**Comment by kvrameshreddy** [comment]
Latest Version 3.0 was installed in my system.

**Comment by vrajat** [comment]
piicatcher has been tested with v2.3.5. v3.0 has incompatible changes. Can you downgrade to the latest v2.x? 

Install piicatcher and spacy 2.x in a virtual environment. I'll use this issue to either upgrade to the latest API or set the dependency version correctly.

**Comment by kvrameshreddy** [comment]
Sure @vrajat  i will downgrade spacy and check.

**Comment by kvrameshreddy** [comment]
Now i am getting the following error
![third_error](https://user-images.githubusercontent.com/49742709/108503103-d3b11680-72d9-11eb-8e5f-75f36c9f2892.PNG)

And how to save the output of piicatcher to a file

**Comment by vrajat** [comment]
The above error message is because `tableprint` - the library used to print terminal may not be compatible with putty or powershell.

This [doc page](https://tokern.io/docs/piicatcher/3-catalog) explains the various options. Use `--catalog-file` to store to a file.

Closing this issue hoping that this will resolve your issue. Please reopen if you still face problems.
