### ISSUE TITLE
Feature Request: Support for binary formats like PDFs and XLS

### ISSUE THREAD

**Issue by shaunakv1** [tokern/piicatcher#138]
Is it a possibility to add support for scanning binary formats (primarily PDF and XLS) for PII?

**Comment by vrajat** [comment]
Hi @shaunakv1 
I started this project by scanning databases and files. Scanning files has not been a popular feature and it has hard to support given the different number of file systems and file formats that are out there. Along with the complexity of supporting multiple databases it is making the project too complex. So I've decided to focus only on supporting databases. I am making changes to the documentation to reflect this change in focus.

It is better to start a new project that only supports file systems and file formats. Happy to collaborate on such a project.
