### ISSUE TITLE
ImportError: cannot import name 'scan_file_object' from 'piicatcher'

### ISSUE THREAD

**Issue by didizlatkova** [tokern/piicatcher#140]
I want to use piicatcher on files, not on databases, but there seems to be no **scan_file_object** method implemented.
I'm using the example code from the README file:

```
pip install piicatcher
from piicatcher import scan_file_object
>>> ImportError: cannot import name 'scan_file_object' from 'piicatcher'
```

**Comment by vrajat** [comment]
Hi @didizlatkova 
I have removed support for files. File support was buggy and hard to maintain given the numerous filesystem protocols. PIICatcher only has support for databases and data warehouses. I am in the process of updating all docs and descriptions.

Sorry for the confusion.

**Comment by vrajat** [comment]
If you want to scan databases, then change the import statement to 

    from piicatcher import scan_database

I've updated the README as well.

**Comment by didizlatkova** [comment]
Hi, thanks for the clarifications. My usecase is very simple - I want to scan a list of texts for PII, the texts are not in a database, that's why I was going for the file option. Is there an easy way to expose an API to run on just text input?

**Comment by vrajat** [comment]
You should consider microsoft/presidio which has much better support for scanning text and images. This is also another reason why I removed support for files. Presidio is better at it.
