### ISSUE TITLE
TypeError: reduce() of empty sequence with no initial value

### ISSUE THREAD

**Issue by yourssvk** [tokern/piicatcher#141]
Guess this is a bug with pii catcher - the schema has thousands fo tables and it hits this - havent looked at the code yet:

2787833 DEBUG:root:has_pii <piicatcher.explorer.metadata.Column object at 0x132e4ea60> has set()
2787834 DEBUG:root:has_pii <piicatcher.explorer.metadata.Column object at 0x132e4eac0> has set()
2787835 Traceback (most recent call last):
2787836   File "/Users/***/.env/bin/piicatcher", line 8, in <module>
2787837     sys.exit(cli())
2787838   File "/Users/***/.env/lib/python3.9/site-packages/click/core.py", line 829, in __call__
2787839     return self.main(*args, **kwargs)
2787840   File "/Users/***/.env/lib/python3.9/site-packages/click/core.py", line 782, in main
2787841     rv = self.invoke(ctx)
2787842   File "/Users/***/.env/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
2787843     return _process_result(sub_ctx.command.invoke(sub_ctx))
2787844   File "/Users/***/.env/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
2787845     return ctx.invoke(self.callback, **ctx.params)
2787846   File "/Users/***/.env/lib/python3.9/site-packages/click/core.py", line 610, in invoke
2787847     return callback(*args, **kwargs)
2787848   File "/Users/***/.env/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
2787849     return f(get_current_context(), *args, **kwargs)
2787850   File "/Users/***/.env/lib/python3.9/site-packages/piicatcher/explorer/databases.py", line 113, in cli
2787851     RelDbExplorer.dispatch(ns)
2787852   File "/Users/***/.env/lib/python3.9/site-packages/piicatcher/explorer/explorer.py", line 63, in dispatch
2787853     cls.output(ns, explorer)
2787854   File "/Users/***/.env/lib/python3.9/site-packages/piicatcher/explorer/explorer.py", line 69, in output
2787855     tableprint.table(explorer.get_tabular(ns.list_all), headers)
2787856   File "/Users/***/.env/lib/python3.9/site-packages/tableprint/printer.py", line 132, in table
2787857     max_data_width = max_width(chain(*data), format_spec)
2787858   File "/Users/***/.env/lib/python3.9/site-packages/tableprint/utils.py", line 118, in max_width
2787859     return reduce(max, map(compute_width, data))
2787860 TypeError: reduce() of empty sequence with no initial value

**Comment by vrajat** [comment]
Closing this as I've rewritten most of the code and released a new version including the console printing logic.
