### ISSUE TITLE
Filters for schema and table are not working when running from CLI for aws

### ISSUE THREAD

**Issue by ghost** [tokern/piicatcher#142]
We are using cli to run piicatcher aws. We need to scan only particular schema/table. To do so, we followed the instructions in the documentation: https://tokern.io/docs/piicatcher/include_exclude_lists
It seems, that the piicatcher scans all the tables, because we are getting errors about the tables, that shouldn't be scanned:
`pyathena.error.OperationalError: HIVE_INVALID_METADATA: Hive metadata for table some_table_name is invalid: Table descriptor contains duplicate columns.`
To fix this we tried different ways of running the command:
```
-n schema_name -t table_name
--schema ("schema_name",) --table ("table_name",)
--schema=("schema_name",) --table=("table_name",)
```

but we are still getting the same error for that table, that shouldn't be present in the search.
Then we tried to exclude the table with` -T some_table_name`, but it still throws the same error. The same happens when we exclude the schema, where this table is located. We do not need to scan that table, but we somehow can't exclude it from the search.

Could you please take a look at this?

**Comment by vrajat** [comment]
Are you running piicatcher on AWS Athena or AWS Glue?

**Comment by okzz** [comment]
Hi @vrajat, I'm a colleague of @St-Jester. it's AWS Athena

**Comment by vrajat** [comment]
I re-ran tests for include/exclude. Also another user successfully used include/exclude on redshift. So the base logic is working. I think the problem is specific to Athena. Can you check if cases differ in the exclude args vs the table name returned by Athena? 

The names are matched using python re.

**Comment by vrajat** [comment]
I've released a new version that revamps the design and removes custom code for Athena. It uses sqlalchemy to connect and a common code base for include/exclude. I've tested the common code base. Can you run again and check?
