### ISSUE TITLE
setup.py file is missing from master 

### ISSUE THREAD

**Issue by kirill-andr** [tokern/piicatcher#143]
I thinks the setup.py file is missing from master branch. I do not see it in Git and also in the cloned directory.
also missing: requirements.txt

**Comment by vrajat** [comment]
Piicatcher uses poetry. Instead of setup.py, it uses pyproject.toml

**Comment by kirill-andr** [comment]
@vrajat thank you. Would you be able to update documentation and installation instructions, which still refer to setup.py

**Comment by vrajat** [comment]
Ah - I am in the process of updating docs. I'll keep track of this one as well. 


Can you paste the error message?

**Comment by vrajat** [comment]
I've update the docs at https://tokern.io/docs/piicatcher/installation
