### ISSUE TITLE
Alternate authentication methods for Athena

### ISSUE THREAD

**Issue by vrajat** [tokern/piicatcher#153]
Working, thanks. I have now another issue - i can only use STS token based auth. For 0.15.0 i was able to correct code to add session token support because different pyathena connection method has been used, but for 0.16+ it is SQLAlchemy based rest access and sesson token seem to be not supported at all by AWS.

__Originally posted by @albert-salman in https://github.com/tokern/piicatcher/issues/151#issuecomment-976710302__

**Comment by vrajat** [comment]
@albert-salman can you explain the changes you had to make? Sqlalchemy+pyathena should support all the methods

**Comment by albert-salman** [comment]
In 0.15 was pyathena "connect" method, like that
cursor = connect(aws_access_key_id="YOUR_ACCESS_KEY_ID",
                 aws_secret_access_key="YOUR_SECRET_ACCESS_KEY",
                 **aws_session_token="YOUR_SESSION_TOKEN"**,
                 s3_staging_dir="s3://YOUR_S3_BUCKET/path/to/",
                 region_name="us-west-2").cursor()

 starting 0.16 you use SQLAlchemy which use REST and this seem never supported STS token-based auth

conn_str = "awsathena+rest://{aws_access_key_id}:{aws_secret_access_key}@athena.{region_name}.amazonaws.com:443/"\
           "{schema_name}?s3_staging_dir={s3_staging_dir}"
engine = create_engine(conn_str.format(
    aws_access_key_id=quote_plus("YOUR_ACCESS_KEY_ID"),
    aws_secret_access_key=quote_plus("YOUR_SECRET_ACCESS_KEY"),
    region_name="us-west-2",
    schema_name="default",
    s3_staging_dir=quote_plus("s3://YOUR_S3_BUCKET/path/to/")))

So i guess without removing SQLAlchemy STS token-based auth will not work.

**Comment by vrajat** [comment]
What changes did you have to make in 0.15 to make it work in STS? 

As per pyathena docs, it should be possible to use other methods through sqlalchemy. Piicatcher has to be fixed and I am trying to understand what changes I need to make to help you to continue to use STS method. 

This is the quote from pyathena README:

If you do not specify aws_access_key_id and aws_secret_access_key using instance profile or boto3 configuration file

**Comment by albert-salman** [comment]
Yes, but STS auth require to use also Session Token in addition to key and secret.
As i said i added session token to connect method (and other places required to pass it from cli arg down to this method)
    def _open_connection(self):
        return pyathena.connect(
            aws_access_key_id=self.config.access_key,
            aws_secret_access_key=self.config.secret_key,
            **aws_session_token=self.config.session_token,**
            s3_staging_dir=self.config.staging_dir,
            region_name=self.config.region,
        )

But with SQLAlchemy (which uses Athena REST API) this will not work. It is using different mechanism for auth where no place to specify session token (https://github.com/laughingman7743/PyAthena/blob/master/pyathena/sqlalchemy_athena.py).

So you need either to go back to non-SQLAlchemy or state that STS token based auth not supported.

**Comment by albert-salman** [comment]
Hmm, looks like it can be fixed using following method
https://github.com/laughingman7743/PyAthena/issues/54

When no creds are specified in connection string it will read then using boto3 credential fetch mechism, so if e.g. ENV vars configured it should work.

For piicatcher this mean to allow to omit creds in CLI so that boto3 ones read. But testing required.

**Comment by vrajat** [comment]
I agree. Also you can set credentials through a config file at ~/.aws/config (https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html) 

Let me make sure that piicatcher can accept empty access and secret tokens and create the correct URL. Then you can try with environment variables or config file?

**Comment by albert-salman** [comment]
Yep, would be great.

**Comment by vrajat** [comment]
Please try version 0.17.3 by setting the creds in environment variables or in `~/.aws/config` as per boto3 docs and NOT specifying `aws_access_key_id` and `aws_secret_access_key`

**Comment by albert-salman** [comment]
Hello,
Still require keys:
(piic) piic $ piicatcher scan athena --s3-staging-dir "s3://aws-athena-query-results"  --name PIIscan --region-name "us-east-1" --include-schema "myschema"
Usage: piicatcher scan athena [OPTIONS]
Try 'piicatcher scan athena --help' for help.

Error: Missing option '--aws-access-key-id'.

**Comment by vrajat** [comment]
I've released `0.17.4`. please give that a try.

**Comment by albert-salman** [comment]
hm, quick test - not working
sqlalchemy.exc.DatabaseError: (pyathena.error.DatabaseError) An error occurred (UnrecognizedClientException) when calling the StartQueryExecution operation: The security token included in the request is invalid.

looks like creds were not found (neither from config nor from ENVs)

looks like a test required outside of piicatcher to know for sure

**Comment by vrajat** [comment]
Agree. Unclear if it is a setup or a piicatcher problem. I have ensured the connection string looks correct as per docs.
