### ISSUE TITLE
shallow scan followed by deep scan causes pk/ uk violations (and possibly viceversa)

### ISSUE THREAD

**Issue by yourssvk** [tokern/piicatcher#164]
shallow scan followed by deep scan causes pk/ uk violations (and possibly viceversa)

**Comment by vrajat** [comment]
I've run shallow and deep scans interchangeably multiple times. Do you have a stack trace or any other information that can be helpful?

**Comment by yourssvk** [comment]
Please park this one aside, will get the trace next time...

**Comment by jhecking** [comment]
Not able to reproduce. Closing as won't fix.
