### ISSUE TITLE
Scan snowflake PII catcher

### ISSUE THREAD

**Issue by astha74** [tokern/piicatcher#170]
I am using PII checker lib for scanning pii data in snowflake database.
https://github.com/tokern/piicatcher][1]

but **scan_snowflake** function is internally creating url with postgreSQL
here is my code

```
catalog_params = {"app_dir": ":memory:"}
output = scan_snowflake(catalog_params=catalog_params, name="pii_db",
                        username={snowflake_username}, password={snowflake_password},
                        database={snowflake_database}, warehouse=args.warehouse,
                        role=args.role, account=args.account)
print(output)
```
Can anyone please tell how to get PII data of snowflake using PII catcher API?

**Comment by vrajat** [comment]
My guess is that there is another source with the name `pii_db` which is a postgres database. The code internally runs this if condition:

            try:
                source = catalog.get_source(name)
            except NoResultFound:
                source = catalog.add_source(
                    name=name,
                    username=username,
                    password=password,
                    database=database,
                    account=account,
                    warehouse=warehouse,
                    role=role,
                    source_type="snowflake",
                )

So if it finds a source with the name `pii_db` it reuses that record. Can you try with a different name?
