### ISSUE TITLE
Unable to Connect to Postgres

### ISSUE THREAD

**Issue by rohitcoderCdefense** [tokern/piicatcher#189]
Hi There,

I'm not sure, why i can't connect to postgres using this tool, credentials are correct. Postgres running on same server localhost:5432 used same username and password to login into psql and pgadmin4

Any ideas on this?

<img width="802" alt="image" src="https://user-images.githubusercontent.com/104613917/171996534-ca6ecf20-8950-4275-bfec-f7063d570ec2.png">

**Comment by morty29** [comment]
If you are using docker then localhost is a docker container rather than your host machine, use host.docker.internal instead to access it

**Comment by rohitcoderCdefense** [comment]
@morty29 Sorry, for delay but i am not running with docker, i tested with docker today and your solution works with that, but not working with system postgres

**Comment by vrajat** [comment]
This is problem with settings of postgresql on your local box. However it is hard to guess which setting is missing or misconfigured  in your postgresql setup. Stackoverflow has a few different solutions. Can you try those? As such there is no restriction or known issue with using piicatcher with local postgres.

**Comment by yjagdale** [comment]
Validated with `host.docker.internal` as hostname instead of localhost inside container and working as expected. 
Also we have added [docker-compose.yml](https://github.com/tokern/piicatcher/blob/master/tests/docker-compose.yml) which has databases along with playground container of python. You can use 
```shell
piicatcher catalog add-mysql --name mariadb_password --username root --database piidb --uri host.docker.internal --port 3306 --password ROOT_ACCESS_PASSWORD
```


```shell
piicatcher catalog scan --source-name mariadb_password
```

**Comment by yjagdale** [comment]
Closing the issue for now, Please reopen if still face issue.
