### ISSUE TITLE
Not able to see complete data

### ISSUE THREAD

**Issue by jayeshagwan1** [tokern/piicatcher#33]
I followed the installation steps. Tried to run on files and db both, but getting the same output 
![image](https://user-images.githubusercontent.com/616970/71081469-41812000-21b5-11ea-8ccd-84d9f3b2ba8d.png)

Can anyone help on what I am missing ?

**Comment by vrajat** [comment]
I've found a bug. The application does not handle a single file correctly. I've been testing with a directory of files. I'll release a new version with the fix asap.

    piicatcher files --path tests/samples/ --output-format json
    [
      {
        "Mime/Type": "text/plain",
        "path": "tests/samples/sample-data.csv",
        "pii": [
          {
            "__enum__": "PiiTypes.EMAIL"
          },
          {
            "__enum__": "PiiTypes.CREDIT_CARD"
          },
          {
            "__enum__": "PiiTypes.PERSON"
          },
          {
            "__enum__": "PiiTypes.LOCATION"
          },
          {
            "__enum__": "PiiTypes.BIRTH_DATE"
          }
        ]
      }
    ]

    piicatcher files --path tests/samples/sample-data.csv --output-format json
    []

**Comment by vrajat** [comment]
I've released a new version - 0.6.1. Please try it out and reopen the issue if it still doesnt work. Can you open a new issue for databases with details ? I'll take a look.

**Comment by jayeshagwan1** [comment]
Thanks @vrajat. json format working fine.

![image](https://user-images.githubusercontent.com/616970/71143306-1859a180-2240-11ea-807b-6d5f5ac85487.png)

Can we format ascii_table ?

![image](https://user-images.githubusercontent.com/616970/71143383-666ea500-2240-11ea-9eb8-533756f53962.png)

I will open a new issue for databases with details.
