### ISSUE TITLE
Getting error while having deep scan mysql db

### ISSUE THREAD

**Issue by vrajat** [tokern/piicatcher#41]
Getting error while having deep scan mysql db

![image](https://user-images.githubusercontent.com/616970/71232924-e61c7280-2319-11ea-9c77-4c07eccc43ac.png)

_Originally posted by @jayeshagwan1 in https://github.com/tokern/piicatcher/issues/36#issuecomment-567797329_

**Comment by jayeshagwan1** [comment]
Thanks @vrajat! Its working now!!!
