### ISSUE TITLE
Recognize file formats like CSV and JSON and process them appropriately.

### ISSUE THREAD

**Issue by jayeshagwan1** [tokern/piicatcher#44]
I have Password as column in csv file. When I run piicatcher its not detecting as PII and does not show pii in output

**Comment by vrajat** [comment]
This is expected. Piicatcher recognizes passwords by checking column names. It does not yet recognize file formats like csv or json files. Specific processing for these file formats is a good feature. I've added a label and edited the title. Hopefully you dont mind.

**Comment by vrajat** [comment]
Wont do. I am moving focus to databases only.
