### ISSUE TITLE
Need path for saving configurations of db's 

### ISSUE THREAD

**Issue by jayeshagwan1** [tokern/piicatcher#47]
We need path of config file to save the databases configurations or command to set the using cli

**Comment by jayeshagwan1** [comment]
Do we have any standard path for config files or its user specific ?

**Comment by vrajat** [comment]
Can you elaborate? I didn’t understand. Sorry. Does —config work for you?

**Comment by vrajat** [comment]
—config. Documented here https://tokern.io/docs/piicatcher/2-usage

**Comment by jayeshagwan1** [comment]
Below is the error:

![image](https://user-images.githubusercontent.com/616970/72326879-0dc2e880-36d6-11ea-985e-fc2d0fa0a08f.png)


This is my config file contents:
# Common option
log_level=INFO

[mysql]
orm-host="10.10.132.165"
orm-port="3306"
orm-user="Jayesh"
orm-password="Info@999"

**Comment by vrajat** [comment]
Check
https://tokern.io/docs/piicatcher/3-databases

ORM is to output results to a database instead of a file or stdout.

For a database, the values has to be in section [db]

**Comment by jayeshagwan1** [comment]
can you provide sample of command?

**Comment by vrajat** [comment]
https://github.com/tokern/piicatcher/blob/master/tests/test_config_file.py#L10

Check line 14-22 and line 29 for the command line arguments.

**Comment by jayeshagwan1** [comment]
db config I have updated and using this command : **piicatcher --config dbconfig.ini db** 
Getting this:
![image](https://user-images.githubusercontent.com/616970/72331210-d0625900-36dd-11ea-8a76-e67d6c47be67.png)

**Comment by vrajat** [comment]
can you run `piicatcher -l debug --config dbconfig.ini db` ?

Also can you paste the contents of `dbconfig.ini` ? Please remove any secrets from the log output and config file.

**Comment by jayeshagwan1** [comment]
[db]
host="10.10.1XX.XXX"
port="3306"
user="Jayesh"
password="IXXo@XXX"
database="Test"
connection-type="mysql"
output-format="json"
scan-type="deep"
output="/result.txt"
list-all=False

![image](https://user-images.githubusercontent.com/616970/72342131-e37f2400-36f1-11ea-9583-168b181d003d.png)

**Comment by vrajat** [comment]
You definitely have an old version of piicatcher. The help message looks
like an old one. Can you run ‘piicatcher —version’ ?

For the latest help message and how it looks check the docs link.

**Comment by jayeshagwan1** [comment]
![image](https://user-images.githubusercontent.com/616970/72343574-373f3c80-36f5-11ea-9889-d58d38274b31.png)


Now getting this error:
![image](https://user-images.githubusercontent.com/616970/72343473-f3e4ce00-36f4-11ea-834a-6f0c3ee28fe3.png)

**Comment by jayeshagwan1** [comment]
Thanks a lot @vrajat . WOrking now after installing latest version.

![image](https://user-images.githubusercontent.com/616970/72402610-af4d4700-3775-11ea-8f38-1dc50b38aeb9.png)


Cheers !!
