### ISSUE TITLE
One config file for multiple databases/file systems

### ISSUE THREAD

**Issue by jayeshagwan1** [tokern/piicatcher#49]
Can we use one config file for multiple databases/file systems so that the command will be same always for any type of supported system ?

**Comment by vrajat** [comment]
Do you mean something like:

    [db1]
    ....

    [db2]
    ....

And choose one through the command line like ?

    piicatcher --config cfg.ini db --name db1

I am depending on https://pypi.org/project/click-config-file/ for config file to save effort and right now it doesn't support it.

**Comment by jayeshagwan1** [comment]
After migrating to config file, deep search is not working. I have 2 tables in db, but result is showing only 1st table.
![image](https://user-images.githubusercontent.com/616970/72710150-70136180-3b8c-11ea-933a-8c206459641e.png)

![image](https://user-images.githubusercontent.com/616970/72710212-96d19800-3b8c-11ea-8a70-9cf0c6a2ffe1.png)

config file :
[db]
host="10.10.XXX.XXX"
port="3306"
user="XXX"
password="XXXX"
database="XX"
connection-type="mysql"
output-format="json"
scan-type="deep"
list-all=True

**Comment by vrajat** [comment]
Checking. Just to confirm, the second table is listed of command line
arguments are used ? —scan-type?

Or deep scan has completely stopped working?

**Comment by jayeshagwan1** [comment]
Ohh. Even after passing --scan-type in config file, we need to explicitely pass **--scan-type deep** in cli. Then only it works:

![image](https://user-images.githubusercontent.com/616970/72737119-f2b81300-3bc4-11ea-88a4-231fff2f2622.png)

**Comment by vrajat** [comment]
OK. So only the config file part is broken. I’ll fix it.

**Comment by vrajat** [comment]
I made a mistake in documentation. It should `scan_type` and not `scan-type`. Can you give it a try with `scan_type` ? Fixing the docs

**Comment by jayeshagwan1** [comment]
Its working fine now. Just one thing. It takes around 6-10 min to return the result

**Comment by vrajat** [comment]
closing as piicatcher uses a catalog to store database info.
