### ISSUE TITLE
Support Include/Exclude Lists 

### ISSUE THREAD

**Issue by vrajat** [tokern/piicatcher#56]
Athena is working for shallow type scan. For deep scan it throws below error:
HIVE_UNKNOWN_ERROR: All access to this object has been disabled (Service: Amazon S3; Status Code: 403; Error Code: AllAccessDisabled; Request ID: 

Is there any parameter in config where we can pass specific DB to scan ?

_Originally posted by @jayeshagwan1 in https://github.com/tokern/piicatcher/issues/55#issuecomment-582275163_

**Comment by jayeshagwan1** [comment]
Thanks. Parameter in config will work na ?

**Comment by jayeshagwan1** [comment]
I tried providing schema and table name to check if it works. I am getting error :

raise OperationalError(query_execution.state_change_reason)                  pyathena.error.OperationalError: SYNTAX_ERROR: line 1:8: Column 'request_timestamp' cannot be resolved
--


I don't   **request_timestamp** column.

**Comment by vrajat** [comment]
I just merged it to master. Can you downloading the code and run `python setup.py develop` in virtualenv ?

`--help` should provide enough docs. Config files are also supported

**Comment by jayeshagwan1** [comment]
After python setup.py develop, tried running help, but not getting updated help:

![image](https://user-images.githubusercontent.com/616970/74136790-ba7c8100-4c14-11ea-929b-8506083de4b1.png)

**Comment by vrajat** [comment]
oh - can you try `piicatcher db --help` ? I have forgotten to support it in aws. I'll add it asap

**Comment by jayeshagwan1** [comment]
My config, I added
list_all=True
schema="temp"
table="pii_data"

Tried running with config:

![image](https://user-images.githubusercontent.com/616970/74137265-7ccc2800-4c15-11ea-9a8f-5e48ffa46175.png)


![image](https://user-images.githubusercontent.com/616970/74137111-41c9f480-4c15-11ea-97bb-9abc625529d4.png)

**Comment by vrajat** [comment]
Yea- I forgot to add it to aws. Fixing that now.

**Comment by jayeshagwan1** [comment]
> `piicatcher db --help`

For db its working fine 👍 
![image](https://user-images.githubusercontent.com/616970/74137443-d5032a00-4c15-11ea-8b6c-7ec1ff012b6a.png)

Also is the above mentioned params for config are correct ?

**Comment by vrajat** [comment]
yes. config looks good.

**Comment by jayeshagwan1** [comment]
Getting below error:
current_schema.tables.append(current_table) AttributeError: 'Schema' object has no attribute 'tables'
--

**Comment by vrajat** [comment]
is there a line number ? Stack trace ?

**Comment by jayeshagwan1** [comment]
![image](https://user-images.githubusercontent.com/616970/74139444-5f00c200-4c19-11ea-9df9-4abbb6d8c05c.png)

**Comment by vrajat** [comment]
I found a gap in my testing. I'll add a test and fix the bug.
