### ISSUE TITLE
schema and table from config is not filtering tables in scan.

### ISSUE THREAD

**Issue by vrajat** [tokern/piicatcher#65]
Even after passing schema and table from config, its still looking into all tables. It should fetch only mentioned schema and table.

_Originally posted by @jayeshagwan1 in https://github.com/tokern/piicatcher/issues/63#issuecomment-585566712_

**Comment by vrajat** [comment]
I think I have found the problem. Can you write the config file as follows for schema and table?

    [aws]
    ....
    schema=('taxidata',)
    table=('csv_trip_data',)

The problem is that python is considering 'taxidata' as a list of ['t', 'a', 'x', 'i', ...] So if the name has any of these characters, then it is selected. This is not intuitive but is a language feature. I dont know how I can stop it from doing that.

**Comment by jayeshagwan1** [comment]
Now Its showing data for required table and for rest it is showing empty. 
@vrajat Thanks a lot !!! 
Some minor observations are there. For some columns its showing wrong PII type.

[shallow_scan.txt](https://github.com/tokern/piicatcher/files/4197991/shallow_scan.txt)
[deep_scan.txt](https://github.com/tokern/piicatcher/files/4197992/deep_scan.txt)
