### ISSUE TITLE
`pip install piicatcher` fails on Python 3.8 "pymssql install fails"

### ISSUE THREAD

**Issue by plasx** [tokern/piicatcher#72]
piicatcher is failing to install on python 3.8.1. (also fails on 3.7). Fails when reaching pymssql package installation. In an attempt to get around it, I tried to install earlier versions of pymssql as listed below:
```
pip install pymssql==1.0.0
pip install pymssql==1.0.1
pip install pymssql==1.0.2
pip install pymssql==1.0.3
pip install pymssql==2.0.0
pip install pymssql==2.0.1
pip install pymssql==2.1.0
pip install pymssql==2.1.1
pip install pymssql==2.1.2
pip install pymssql==2.1.3
pip install pymssql==2.1.4rc1
pip install pymssql==2.1.4
```
But all led to the same error:
```
$ pip install piicatcher
...
Collecting pymssql<3.0 (from piicatcher)
  Using cached https://files.pythonhosted.org/packages/2e/81/99562b93d75f3fc5956fa65decfb35b38a4ee97cf93c1d0d3cb799fffb99/pymssql-2.1.4.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /Users/drivera017/dev/testing-grounds/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/nl/gjvm7nyx4szc8dt9d5fgdk_w0000gn/T/pip-install-7lfmffe3/pymssql/setup.py'"'"'; __file__='"'"'/private/var/folders/nl/gjvm7nyx4szc8dt9d5fgdk_w0000gn/T/pip-install-7lfmffe3/pymssql/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /private/var/folders/nl/gjvm7nyx4szc8dt9d5fgdk_w0000gn/T/pip-install-7lfmffe3/pymssql/
    Complete output (7 lines):
    /Users/drivera017/dev/testing-grounds/venv/lib/python3.8/site-packages/setuptools/dist.py:45: DistDeprecationWarning: Do not call this function
      warnings.warn("Do not call this function", DistDeprecationWarning)
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/nl/gjvm7nyx4szc8dt9d5fgdk_w0000gn/T/pip-install-7lfmffe3/pymssql/setup.py", line 88, in <module>
        from Cython.Distutils import build_ext as _build_ext
    ModuleNotFoundError: No module named 'Cython'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by plasx** [comment]
May relate to https://github.com/tokern/piicatcher/issues/29

**Comment by vrajat** [comment]
I am trying to reproduce this error. In the meantime, to get unblocked can you run `pip install Cython` and then check?

**Comment by vrajat** [comment]
I was able to reproduce the issue. The difference is that, on my machine python wheels are used while on your machine the package is built from source code:

    TMPDIR=/tmp/piptmp/ pip install --no-binary :all: --no-cache-dir --build=/tmp/piptmp/build  piicatcher
    Collecting piicatcher
      Downloading
    https://files.pythonhosted.org/packages/....507bc12/piicatcher-0.8.1.tar.gz
        .....
    Collecting pymssql<3.0 (from piicatcher)
      Downloading 
    https://files.pythonhosted.org/packages/...../pymssql-2.1.4.tar.gz (691kB)
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
          File "/tmp/piptmp/build/pymssql/setup.py", line 88, in <module>
            from Cython.Distutils import build_ext as _build_ext
        ModuleNotFoundError: No module named 'Cython'
        
        ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/piptmp/build/pymssql/

A simple `pip install ...` uses a python wheel 

    Collecting pymssql<3.0 (from piicatcher)
      Downloading
    https://files.pythonhosted.org/packages/.../pymssql-2.1.4-cp37-cp37m-manylinux1_x86_64.whl (1.4MB)
