### ISSUE TITLE
Documentation links do not work

### ISSUE THREAD

**Issue by food-spotter** [tokern/piicatcher#78]
The links to the documentation in the README do not work. They end up displaying a page with the following message:
```xml
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
</Error>
```

**Comment by vrajat** [comment]
Fixed now. I had pushed a bad version of the website. Thanks for reporting the broken link. Please give feedback if PIICatcher is useful to you.
