### ISSUE TITLE
include schema filter is not working on redshift

### ISSUE THREAD

**Issue by food-spotter** [tokern/piicatcher#79]
I'm finding that piicatcher fails to apply include schema argument. This has been tried using the `-n`, `--schema` via cli as well as `schema` via config file.

I have the following database structure in redshift:
```
prod_database
│
├── schema_a
│   ├── table_1
│   ├── table_2
│   └── table_3
│
├── schema_b
    ├── table_x
    ├── table_y
    └── table_z
```
My config file looks like this:
```
[db]
host="***"
port="5439"
user="***"
password="***"
database="prod_database"
connection_type="redshift"
scan_type="shallow"
list_all=False
schema=("schema_a",)
exclude_schema=("schema_b",)
```

However the returned output shows that piicatcher scanned through both schemas.

**Comment by vrajat** [comment]
The config looks correct to me. This should work. I’ll test it again on my setup.

**Comment by vrajat** [comment]
I am able to reproduce the bug. I'll release a fix soon.

**Comment by vrajat** [comment]
@food-spotter Did the fix work for you ? Were you able to use piicatcher successfully ? Please tell me if piicatcher worked for your use case.

**Comment by food-spotter** [comment]
Thanks, it is now working as expected 👍 🎉
