### ISSUE TITLE
ascii_table format not working

### ISSUE THREAD

**Issue by jayeshagwan1** [tokern/piicatcher#84]
Getting below error when trying output format as ascii_table

\Programs\Python\Python37\lib\encodings\cp 1252.py", line 19, in encode                                                         return codecs.charmap_encode(input,self.errors,encoding_table)[0]            
UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-42: character maps to
--

**Comment by vrajat** [comment]
https://stackoverflow.com/questions/27092833/unicodeencodeerror-charmap-codec-cant-encode-characters gives a good answer. 

This is a good but very long read on encoding in Python: https://realpython.com/python-encodings-guide/

In Linux, the default encoding is utf-8 but not in windows.

    # Mac OS X High Sierra
    import locale
    locale.getpreferredencoding()
    'UTF-8'

    # Windows Server 2012; other Windows builds may use UTF-16
    import locale
    locale.getpreferredencoding()
    'cp1252

I’ll force all I/O to use utf-8 but you maybe able to workaround by setting python system encoding to utf-8 (you’ll have to search the web for instructions)

**Comment by jayeshagwan1** [comment]
So I found that if we use bash, we get the above error. But If we use cmd or powershell, it gives ascii table:
![image](https://user-images.githubusercontent.com/616970/78218696-d5b09200-74db-11ea-85ef-3be570f94669.png)
