### ISSUE TITLE
Can we show data in output ?

### ISSUE THREAD

**Issue by jayeshagwan1** [tokern/piicatcher#85]
Is it possible to provide data in output ?

**Comment by vrajat** [comment]
Can you provide more details? Output of ascii table ? Example ?

**Comment by jayeshagwan1** [comment]
In any format, can we show data along with this:
![image](https://user-images.githubusercontent.com/616970/78256857-b5ea8f80-7516-11ea-90af-327ae4cf9802.png)

**Comment by vrajat** [comment]
All rows and all columns ?

**Comment by vrajat** [comment]
@jayeshagwan1 I have sometime this week to work on the project. Can you give me an example ? Do you want to replace has_pii ? Show data from all rows ? I am not clear about the requirements.
