### ISSUE TITLE
unable to get pii columns from mysql

### ISSUE THREAD

**Issue by hsdqa** [tokern/piicatcher#88]
Tried running the piicatcher on mysql db but it did not list any columns

| TABLE_SCHEMA  | TABLE_NAME  | COLUMN_NM  | DATA_TYPE |
|-----------------  |----------------|----------------|-------------|
| testpiicatcher | cstmr      | fl_nm       | varchar   |
| testpiicatcher | cstmr      | fname       | varchar   |
| testpiicatcher | cstmr      | lname       | varchar   |

The output is blank and has not listed, was expecting 2 columns should be listed as having pii i.e. 
f**name|lname** as they follow the regex pattern mentioned in

using python 3.8.2 and on macosx

**Comment by vrajat** [comment]
Yes. It should detect those column names. I’ll try to reproduce the bug.

**Comment by vrajat** [comment]
I tried to reproduce in #89 but it worked for me. Can you paste the command line and output ? Please remove any secrets.

**Comment by hsdqa** [comment]
@vrajat seems its working now, not really sure what the issue was, I just tried cloning the repo again and running it and it seems to be working fine now, Thanks!

But just an observation that I had, I have 2 tables cstmr(id, fname,lname,fl_name) and person(id,person,st)
cstmr.fl_nm = concatenate(fname |" " | lname and st = STATE(e.g. New York)

**Output using deep output is** 
| Schema  | table  | column  | has_pii |
|---------  |-------|--------|--------|
| testpiicatcher | cstmr        |  fl_nm   | 1 |
| testpiicatcher | person      | st          | 1 |

**and using shallow**
| Schema  | table  | column  | has_pii |
|---------  |-------|--------|--------|
| testpiicatcher | cstmr        |  fname   | 1 |
| testpiicatcher | cstmr      | lname          | 1 |

My expectation was with deep along with the output of shallow, person.st should be listed because it would find LOCATION and fl_nm as PERSON

**Comment by vrajat** [comment]
Yes. There is a difference. Check #69 where I have explained why. I’ll fix it soon. 

I have another request: Can you take this survey: https://forms.gle/Ns6QSNvfj3Pr2s9s6 ? 

This will help understand how to improve this project.

**Comment by hsdqa** [comment]
Thanks for referencing the issue, also have submitted the form survey.
