### ISSUE TITLE
Developer setup not working

### ISSUE THREAD

**Issue by jayeshagwan1** [tokern/piicatcher#91]
Followed the steps mentioned in documentation, but getting below error on windows 10:

![image](https://user-images.githubusercontent.com/616970/80458581-a2341c80-894e-11ea-8b5a-c9e8d5cdf7f7.png)

**Comment by vrajat** [comment]
I havent run this setup in a while. It used to work for me. I tried a new setup and it failed with another error. I am investigating.

**Comment by jayeshagwan1** [comment]
I was able to resolve this issue. Issue was with python-magic library. Need to uninstall python-magic and install **python-magic-bin==0.4.14**. **Note: I am facing this issue while command-line application also on windows.**
After installing python-magic-bin==0.4.14 I need to reinstall python-magic again.
